# Informações principais do projeto
site_name: terraglue
site_url: https://terraglue.readthedocs.io/pt/latest/
site_author: Thiago Panini
site_description : >-
  Um módulo Terraform open source capaz de permitir a
  fácil implantação de jobs Glue para realização de
  processos de ETL na AWS.

# Informações do repositório com o código fonte
repo_name: ThiagoPanini/terraglue
repo_url: https://github.com/ThiagoPanini/terraglue

# Copyright
copyright: |
  Copyright &copy; 2023-2024 <a href="https://github.com/ThiagoPanini"  target="_blank" rel="noopener">Thiago Panini</a>

# Configurações extras da documentação
extra:
  # Redes sociais no footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ThiagoPanini
      name: Thiago Panini no Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thiago-panini/
      name: Thiago Panini no LinkedIn
    - icon: fontawesome/brands/hashnode
      link: https://panini.hashnode.dev/
      name: Blog panini-tech-lab no Hashnode
  
  # Google Analytics
  analytics:
    provider: google
    property: G-THYKY7057T
    feedback:
      title: Esta página foi útil?
      ratings:
        - icon: material/thumb-up-outline
          name: Yes, awesome!
          data: 1
          note: >-
            Obrigado pelo seu feedback!
        - icon: material/thumb-down-outline
          name: No, it needs improvements!
          data: 0
          note: >-
            Obrigado pelo seu feedback!

# Configuração do tema
theme:
  name: material

  # Diretório adicional para customização do tema
  custom_dir: docs/_overrides

  # Customizando ícone no header da página
  icon:
    logo: custom/custom-icon-32px
  
  # Customizando favicon (ícone da aba)
  favicon: _assets/imgs/logo/logo-sem-nome.png

  # Configurando paleta de cores
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Toque para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Toque para modo claro

  # Configurando features da documentação
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy

# Navegação
nav:
  - Home:
    - datadelivery: index.md
    
  - Quickstart:
    - Overview: quickstart/overview.md
    - Variáveis do Módulo: quickstart/variaveis.md
    - Detalhes Adicionais:
      - Arquitetura: quickstart/arquitetura.md
      - Design: quickstart/design.md

  - Contribuindo: contribuindo/contribuindo.md

# Configurando extensões
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - markdown.extensions.tables
  - markdown.extensions.footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search:
      lang: pt
  - mkdocstrings
  - drawio_file
  - glightbox
  - git-committers:
      repository: ThiagoPanini/datadelivery
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css