name: 01 - Validação de estrutura do código

on:
  push:
    branches:
      - develop

jobs:
  setup-python:
    name: Setup Python 3.10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalação do Python 3.10
        uses: actions/setup-python@v3

      - name: Instalação das Dependências
        run: |
          python -m pip install --upgrade pip
          pip install flake8
    
