name: "🚀 CI release drafter"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:    
  update-release-draft:
    name: update-relase-draft
    runs-on: ubuntu-latest
    
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: configs/release-drafter.yml

      
