name: 🤖 ChatGPT Code Review

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  chatgpt-code-review:
    name: chatgpt-code-review
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Code Review
        uses: cirolini/chatgpt-github-actions@v1
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
      